name: Greet New Contributor

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Greet Contributor
        run: |
          PR_AUTHOR=$(jq --raw-output .pull_request.user.login "$GITHUB_EVENT_PATH")
          COMMENT="Hello @${PR_AUTHOR}, thank you for your first pull request! 🎉🎉🎉 We appreciate your contribution!"
          
          # Comment on the pull request
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"body\": \"$COMMENT\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
